version: "3.7"
services:
  web:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
