version: "3.7"
services:
  web:
    image: php:7.3-apache
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
