version: "3.7"
services:
  web:
    image: dsifford/php-pdo-apache
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    volumes:
      - data:/var/lib/mysql
    ports:
      - 22222:80

volumes:
  data:
